// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAC4rvhIXA6f5qKUnqE88xlNNx2aMuI7k4',
    appId: '1:159752927531:web:bbe30d40d1754262d46d6e',
    messagingSenderId: '159752927531',
    projectId: 'pushnotification-4281b',
    authDomain: 'pushnotification-4281b.firebaseapp.com',
    storageBucket: 'pushnotification-4281b.firebasestorage.app',
    measurementId: 'G-1X0D4914S8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOJzII6H9pb7C5qUSk7xN4dpf6VrgzUYM',
    appId: '1:159752927531:android:556a529508528f23d46d6e',
    messagingSenderId: '159752927531',
    projectId: 'pushnotification-4281b',
    storageBucket: 'pushnotification-4281b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBF8-2OVAyXS5A73N21Rq6Fxk5eu5XcEuk',
    appId: '1:159752927531:ios:5b5f500cabb6836dd46d6e',
    messagingSenderId: '159752927531',
    projectId: 'pushnotification-4281b',
    storageBucket: 'pushnotification-4281b.firebasestorage.app',
    iosBundleId: 'com.example.pushnotification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBF8-2OVAyXS5A73N21Rq6Fxk5eu5XcEuk',
    appId: '1:159752927531:ios:5b5f500cabb6836dd46d6e',
    messagingSenderId: '159752927531',
    projectId: 'pushnotification-4281b',
    storageBucket: 'pushnotification-4281b.firebasestorage.app',
    iosBundleId: 'com.example.pushnotification',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAC4rvhIXA6f5qKUnqE88xlNNx2aMuI7k4',
    appId: '1:159752927531:web:40f715ef409902cdd46d6e',
    messagingSenderId: '159752927531',
    projectId: 'pushnotification-4281b',
    authDomain: 'pushnotification-4281b.firebaseapp.com',
    storageBucket: 'pushnotification-4281b.firebasestorage.app',
    measurementId: 'G-4N8FRKC0E7',
  );
}
